name: "Install osls CLI"
description: "Installs the osls serverless CLI globally for deployment workflows."
author: "Daniel Santana"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  osls-version:
    description: "Version of the osls package to install (SemVer or tag)."
    required: false
    default: "3.59.3"
outputs:
  osls-version:
    description: "Detected osls version after installation."
  osls-path:
    description: "Absolute path to the installed osls binary."
runs:
  using: "composite"
  steps:
    - name: Install bundled osls
      shell: bash
      run: |
        set -euo pipefail
        export BIN_DIR="${{ runner.temp }}/osls/bin"
        echo "BIN_DIR=$BIN_DIR"
        mkdir -p "$BIN_DIR"

        # prefer the checked-in bundle, otherwise download from our releases
        if [ -f "$GITHUB_ACTION_PATH/dist/osls_bundle.js" ]; then
          cp -f "$GITHUB_ACTION_PATH/dist/osls_bundle.js" "$BIN_DIR/osls_bundle.js"
        else
          echo "dist/osls_bundle.js not present in action checkout — downloading release asset"
          curl -fsSL -o "$BIN_DIR/osls_bundle.js" "https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/latest/download/osls_bundle.js"
        fi
        export OSLS_BINARY_PATH="$BIN_DIR/osls"
        echo "OSLS_BINARY_PATH=$OSLS_BINARY_PATH"

        echo '#!/bin/sh' > "$OSLS_BINARY_PATH"
        echo "exec node $BIN_DIR/osls_bundle.js \$@" >> "$OSLS_BINARY_PATH"

        chmod +x "$OSLS_BINARY_PATH"

        # extract packaged node_modules if present (ensures runtime requires resolve)
        if [ -f "$GITHUB_ACTION_PATH/dist/osls_node_modules.tgz" ]; then
          tar -C "$BIN_DIR" -xzf "$GITHUB_ACTION_PATH/dist/osls_node_modules.tgz"
        else
          if curl --head --silent --fail "https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/latest/download/osls_node_modules.tgz" >/dev/null 2>&1; then
            echo "Downloading osls_node_modules.tgz from latest release"
            curl -fsSL -o "$BIN_DIR/osls_node_modules.tgz" "https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/latest/download/osls_node_modules.tgz"
            tar -C "$BIN_DIR" -xzf "$BIN_DIR/osls_node_modules.tgz"
          fi
        fi
        echo "$BIN_DIR" >> "$GITHUB_PATH"

    - name: Install bundled osls (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $bin = "$Env:RUNNER_TEMP\\osls\\bin"
        New-Item -ItemType Directory -Force -Path $bin | Out-Null
        if (Test-Path "$Env:GITHUB_ACTION_PATH\\dist\\osls_bundle.js") {
          Copy-Item -Path "$Env:GITHUB_ACTION_PATH\\dist\\osls_bundle.js" -Destination "$bin\\osls_bundle.js" -Force
        } else {
          Write-Host "dist/osls_bundle.js not present in action checkout — downloading release asset"
          Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/$Env:GITHUB_ACTION_REPOSITORY/releases/latest/download/osls_bundle.js" -OutFile "$bin\\osls_bundle.js"
        }
        $cmd = '@echo off\r\nnode "%~dp0\\osls_bundle.js" %*\r\n'
        Set-Content -Path "$bin\\osls.cmd" -Value $cmd -NoNewline -Encoding Ascii
        Add-Content -Path $Env:GITHUB_PATH -Value $bin

        # extract packaged node_modules if present
        if (Test-Path "$Env:GITHUB_ACTION_PATH\\dist\\osls_node_modules.tgz") {
          tar -C $bin -xzf "$Env:GITHUB_ACTION_PATH\\dist\\osls_node_modules.tgz"
        } else {
          $asset = "https://github.com/$Env:GITHUB_ACTION_REPOSITORY/releases/latest/download/osls_node_modules.tgz"
          try {
            Invoke-WebRequest -UseBasicParsing -Uri $asset -OutFile "$bin\\osls_node_modules.tgz" -ErrorAction Stop
            tar -C $bin -xzf "$bin\\osls_node_modules.tgz"
          } catch {
            Write-Host "no node_modules tarball found in release; continuing"
          }
        }

    - id: verify-unix
      name: Verify Installation (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Multi-line-safe output for osls-version
        echo "osls-version<<EOF" >> $GITHUB_OUTPUT
        osls --version >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Path is single-line but keep consistent
        echo "osls-path=$(which osls)" >> $GITHUB_OUTPUT

    - id: verify-windows
      name: Verify Installation (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Multi-line-safe output for Windows
        $version = (& osls --version) -join "`n"
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-version<<EOF"
        Add-Content -Path $Env:GITHUB_OUTPUT -Value $version
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "EOF"

        $path = (Get-Command osls).Path
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-path=$path"
