name: "Install osls CLI"
description: "Installs the osls serverless CLI globally for deployment workflows."
author: "Daniel Santana"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  osls-version:
    description: "Version of the osls package to install (SemVer or tag)."
    required: false
    default: "3.59.3"
  args:
    description: "Arguments to pass to the osls command. If provided, osls will be executed with these arguments."
    required: false
  entrypoint:
    description: "Override the default entrypoint (osls)."
    required: false
outputs:
  osls-version:
    description: "Detected osls version after installation."
  osls-path:
    description: "Absolute path to the installed osls binary."
runs:
  using: "composite"
  steps:
    - name: Install bundled osls
      shell: bash
      run: |
        set -euo pipefail
        export BIN_DIR="${{ runner.temp }}/osls/bin"
        echo "BIN_DIR=$BIN_DIR"
        mkdir -p "$BIN_DIR"

        # prefer the checked-in bundle, otherwise download from our releases
        if [ -f "$GITHUB_ACTION_PATH/dist/osls_bundle.js" ]; then
          cp -f "$GITHUB_ACTION_PATH/dist/osls_bundle.js" "$BIN_DIR/osls_bundle.js"
        else
          echo "dist/osls_bundle.js not present in action checkout — downloading release asset"
          curl -fsSL -o "$BIN_DIR/osls_bundle.js" "https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/latest/download/osls_bundle.js"
        fi
        export OSLS_BINARY_PATH="$BIN_DIR/osls"
        echo "OSLS_BINARY_PATH=$OSLS_BINARY_PATH"

        echo '#!/bin/sh' > "$OSLS_BINARY_PATH"
        echo "exec node $BIN_DIR/osls_bundle.js \$@" >> "$OSLS_BINARY_PATH"

        chmod +x "$OSLS_BINARY_PATH"
        ln -s "$OSLS_BINARY_PATH" "$BIN_DIR/serverless" || true
        ln -s "$OSLS_BINARY_PATH" "$BIN_DIR/sls" || true

        # extract packaged node_modules if present (ensures runtime requires resolve)
        NODE_MODULES_ARCHIVE="$GITHUB_ACTION_PATH/dist/osls_node_modules.tgz"
        if [ ! -f "$NODE_MODULES_ARCHIVE" ]; then
          echo "dist/osls_node_modules.tgz not found locally. Attempting download..."
          
          # Try to use the action ref (tag) if available, otherwise fallback to latest
          REF_TAG="${GITHUB_ACTION_REF:-latest}"
          # If ref is a branch (e.g. master), it won't have a release, so check first
          DOWNLOAD_URL="https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/download/${REF_TAG}/osls_node_modules.tgz"
          
          if ! curl --head --silent --fail "$DOWNLOAD_URL" >/dev/null 2>&1; then
            echo "Release asset not found for ref '${REF_TAG}', falling back to 'latest'..."
            DOWNLOAD_URL="https://github.com/${GITHUB_ACTION_REPOSITORY}/releases/latest/download/osls_node_modules.tgz"
          fi
          
          echo "Downloading dependencies from $DOWNLOAD_URL"
          if ! curl -fsSL -o "$BIN_DIR/osls_node_modules.tgz" "$DOWNLOAD_URL"; then
            echo "::error::Failed to download osls_node_modules.tgz. Please ensure you are using a valid release tag or that the release assets are available."
            exit 1
          fi
          NODE_MODULES_ARCHIVE="$BIN_DIR/osls_node_modules.tgz"
        fi
        
        echo "Extracting dependencies..."
        tar -C "$BIN_DIR" -xzf "$NODE_MODULES_ARCHIVE"
        echo "$BIN_DIR" >> "$GITHUB_PATH"

    - name: Install bundled osls (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $bin = "$Env:RUNNER_TEMP\\osls\\bin"
        New-Item -ItemType Directory -Force -Path $bin | Out-Null
        if (Test-Path "$Env:GITHUB_ACTION_PATH\\dist\\osls_bundle.js") {
          Copy-Item -Path "$Env:GITHUB_ACTION_PATH\\dist\\osls_bundle.js" -Destination "$bin\\osls_bundle.js" -Force
        } else {
          Write-Host "dist/osls_bundle.js not present in action checkout — downloading release asset"
          Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/$Env:GITHUB_ACTION_REPOSITORY/releases/latest/download/osls_bundle.js" -OutFile "$bin\\osls_bundle.js"
        }
        $cmd = '@echo off\r\nnode "%~dp0\\osls_bundle.js" %*\r\n'
        Set-Content -Path "$bin\\osls.cmd" -Value $cmd -NoNewline -Encoding Ascii
        Copy-Item -Path "$bin\\osls.cmd" -Destination "$bin\\serverless.cmd" -Force
        Copy-Item -Path "$bin\\osls.cmd" -Destination "$bin\\sls.cmd" -Force
        Add-Content -Path $Env:GITHUB_PATH -Value $bin

        # extract packaged node_modules if present
        $localArchive = "$Env:GITHUB_ACTION_PATH\\dist\\osls_node_modules.tgz"
        if (Test-Path $localArchive) {
          tar -C $bin -xzf $localArchive
        } else {
          $ref = $Env:GITHUB_ACTION_REF
          if (-not $ref) { $ref = "latest" }
          $url = "https://github.com/$Env:GITHUB_ACTION_REPOSITORY/releases/download/$ref/osls_node_modules.tgz"
          
          try {
             $req = [System.Net.WebRequest]::Create($url)
             $req.Method = "HEAD"
             $null = $req.GetResponse()
          } catch {
             Write-Host "Release asset not found for ref '$ref', falling back to 'latest'..."
             $url = "https://github.com/$Env:GITHUB_ACTION_REPOSITORY/releases/latest/download/osls_node_modules.tgz"
          }

          Write-Host "Downloading dependencies from $url"
          try {
            Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile "$bin\\osls_node_modules.tgz" -ErrorAction Stop
            tar -C $bin -xzf "$bin\\osls_node_modules.tgz"
          } catch {
            Write-Error "Failed to download osls_node_modules.tgz. Please ensure you are using a valid release tag or that the release assets are available."
            exit 1
          }
        }

    - id: verify-unix
      name: Verify Installation (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # Multi-line-safe output for osls-version
        echo "osls-version<<EOF" >> $GITHUB_OUTPUT
        osls --version >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Path is single-line but keep consistent
        echo "osls-path=$(which osls)" >> $GITHUB_OUTPUT

    - id: verify-windows
      name: Verify Installation (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Multi-line-safe output for Windows
        $version = (& osls --version) -join "`n"
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-version<<EOF"
        Add-Content -Path $Env:GITHUB_OUTPUT -Value $version
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "EOF"

        $path = (Get-Command osls).Path
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-path=$path"

    - name: Run osls command (Unix)
      if: inputs.args != '' && runner.os != 'Windows'
      shell: bash
      env:
        INPUT_ENTRYPOINT: ${{ inputs.entrypoint }}
        INPUT_ARGS: ${{ inputs.args }}
      run: |
        CMD="${INPUT_ENTRYPOINT:-osls}"
        $CMD $INPUT_ARGS

    - name: Run osls command (Windows)
      if: inputs.args != '' && runner.os == 'Windows'
      shell: pwsh
      env:
        INPUT_ENTRYPOINT: ${{ inputs.entrypoint }}
        INPUT_ARGS: ${{ inputs.args }}
      run: |
        $cmd = if ($Env:INPUT_ENTRYPOINT) { $Env:INPUT_ENTRYPOINT } else { "osls" }
        Invoke-Expression "$cmd $Env:INPUT_ARGS"
