name: "Install osls CLI"
description: "Installs the osls serverless CLI globally for deployment workflows."
author: "Daniel Santana"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  osls-version:
    description: "Version of the osls package to install (SemVer or tag)."
    required: false
    default: "3.59.3"
outputs:
  osls-version:
    description: "Detected osls version after installation."
  osls-path:
    description: "Absolute path to the installed osls binary."
runs:
  using: "composite"
  steps:
    - name: Install bundled osls
      shell: bash
      run: |
        set -euo pipefail
        BIN_DIR="${{ RUNNER_TEMP:-/tmp }}/osls/bin"
        mkdir -p "$BIN_DIR"
        cp -f "$(pwd)/dist/osls_bundle.js" "$BIN_DIR/osls_bundle.js"
        cat > "$BIN_DIR/osls" <<EOF
          #!/bin/sh
          exec node "$BIN_DIR/osls_bundle.js" "$@"
        EOF
        chmod +x "$BIN_DIR/osls"
        echo "$BIN_DIR" >> "$GITHUB_PATH"

    - name: Install bundled osls (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $bin = "$Env:RUNNER_TEMP\\osls\\bin"
        New-Item -ItemType Directory -Force -Path $bin | Out-Null
        Copy-Item -Path "$(pwd)\\dist\\osls_bundle.js" -Destination "$bin\\osls_bundle.js" -Force
        $cmd = '@echo off\r\nnode "%~dp0\\osls_bundle.js" %*\r\n'
        Set-Content -Path "$bin\\osls.cmd" -Value $cmd -NoNewline -Encoding Ascii
        Add-Content -Path $Env:GITHUB_PATH -Value $bin

    - id: verify
      name: Verify Installation (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "osls-version=$(osls --version)" >> $GITHUB_OUTPUT
        echo "osls-path=$(which osls)" >> $GITHUB_OUTPUT

    - id: verify
      name: Verify Installation (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $version = (& osls --version) -join "\n"
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-version=$version"
        $path = (Get-Command osls).Path
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "osls-path=$path"
