name: "Install osls CLI"
description: "Installs the osls serverless CLI globally for deployment workflows."
author: "Daniel Santana"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  osls-version:
    description: "Version of the osls package to install (SemVer or tag)."
    required: false
    default: "3.59.3"
outputs:
  osls-version:
    description: "Detected osls version after installation."
  osls-path:
    description: "Absolute path to the installed osls binary."
runs:
  using: "node24"
  main: "dist/index.js"
